(function() {var implementors = {};
implementors["bf"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"bf/common/enum.Error.html\" title=\"enum bf::common::Error\">Error</a>",synthetic:true,types:["bf::common::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"bf/common/enum.Command.html\" title=\"enum bf::common::Command\">Command</a>",synthetic:true,types:["bf::common::Command"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"bf/common/enum.Instruction.html\" title=\"enum bf::common::Instruction\">Instruction</a>",synthetic:true,types:["bf::common::Instruction"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"bf/state/struct.State.html\" title=\"struct bf::state::State\">State</a>",synthetic:true,types:["bf::state::State"]},{text:"impl&lt;'a&gt; !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"bf/rts/struct.RtsState.html\" title=\"struct bf::rts::RtsState\">RtsState</a>&lt;'a&gt;",synthetic:true,types:["bf::rts::RtsState"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"bf/ast/enum.Statement.html\" title=\"enum bf::ast::Statement\">Statement</a>",synthetic:true,types:["bf::ast::Statement"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"bf/rle/enum.Statement.html\" title=\"enum bf::rle::Statement\">Statement</a>",synthetic:true,types:["bf::rle::Statement"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"bf/peephole/enum.Statement.html\" title=\"enum bf::peephole::Statement\">Statement</a>",synthetic:true,types:["bf::peephole::Statement"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"bf/jit/struct.Program.html\" title=\"struct bf::jit::Program\">Program</a>",synthetic:true,types:["bf::jit::Program"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
